apiVersion: v2
name: certificat
description: CertifiCat Helm Chart
type: application
sources:
  - https://gitlab.code.rit.edu/its-operations-public/django-acmev2/charts/
version: 2025.12.1766426460
appVersion: 2025.12.1766426460
