apiVersion: v2
name: certificat
description: CertifiCat Helm Chart
type: application
sources:
  - https://gitlab.code.rit.edu/its-operations-public/django-acmev2/charts/
version: 2026.1.1768504097
appVersion: 2026.1.1768504097
